server:
  port: 8070
mybatis-plus:
  type-aliases-package: com.project.pojo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/psiworm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        service: psi-user
  application:
    name: psi-system
logging:
  level:
    com.project: debug