server:
  port: 8070
mybatis-plus:
  type-aliases-package: com.project.pojo
spring:
  redis:
    host: 192.168.64.181  #假如有集群就不需要在这里再写host了
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/psiworm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        service: hos-system
  application:
    name: hos-system
logging:
  level:
    com.project: debug
